### ISSUE TITLE
Help with Authorization

### ISSUE THREAD

**Issue by hwkerr** [Chris-Kode/myanimelist-api-v2#1]
Hey, I'm pretty new to authentication and only have experience using Passport.js to log in with OAuth 2.0. I'm having trouble understanding where everything goes and figuring out how to apply my knowledge of Passport here.

I'm using express like in your examples and have set up a route for "/auth/mal" and "/auth/mal/callback". I'm successfully accessing the Authorization Dialog page and then the callback route.
Am I correct in thinking that this is where my oauth.accessToken(pkce.code_verifier, pkce.code_challenge)... function should go and that those are the correct parameters? When I put this function in my callback route, I get the following error every time MAL redirects to my callback route:
`{"error":"invalid_request","message":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","hint":"Cannot decrypt the authorization code"}`

Would really appreciate some help with this. Thanks!

**Comment by Chris-Kode** [comment]
CODE => This code is the code that we received in our callback url, in this case "/auth/mal/callback?code=asdokasokdoasodko" you need to take the code parameter and save to the accesstoken.
 
oauth.accessToken(CODE, CODE_CHALLENGE)

**Comment by hwkerr** [comment]
Thanks! helped me realize it's part of the request, so I needed to get it with req.query.code which seems to make it work now. Appreciate the quick response
