### ISSUE TITLE
Error requesting access_token

### ISSUE THREAD

**Issue by anark1stx** [Chris-Kode/myanimelist-api-v2#3]
Following the example on the [README](https://github.com/Chris-Kode/myanimelist-api-v2#initial-stepts-before-use-the-api), in step two, I got it like this:

```
            this.code = this.$route.query.code; // After allowing MAL it redirects to the page you set as redirect uri with the parameter 'code'.
            const oauth = new API.OAUTH(process.env.CLIENT_ID, process.env.CLIENT_SECRET);

            oauth
                .accessToken(this.code, process.env.CODE_CHALLENGE)
                .then((response) => {
                    console.log(response);
                })
                .catch((err) => {
                    console.log(err);
                });
```

Which gives the following error:

```
  {
    error: 'invalid_grant',
    message: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.',
    hint: 'Failed to verify `code_verifier`.'
  }
```

As the hint says, the code_verifier is not valid, and that's because we're passing CODE_CHALLENGE(#4 ), I tried replacing it with the CODE_VERIFIER value, but still get the same error.

Reading the file [Mal_Oauth.js](https://github.com/Chris-Kode/myanimelist-api-v2/blob/master/src/Mal_Oauth/Mal_Oauth.js), I can see that the intended parameter was indeed code_verifier but again, it's not working for me.

**Comment by Chris-Kode** [comment]
Hello @anark1stx sry for the delay, i was watching what was the problem that u told me, but i can execute all fine sending the code_challenge, i think that i need to change the variable's name in the code that  because may cause confusion.

This is the code that i test it

```javascript
const express = require("express");
const app = express();
const port = 3000;
const API = require("@chris-kode/myanimelist-api-v2");
const pkceChallenge = require("pkce-challenge");
const CLIENT_ID = "your-code-client-id";
const oauth = new API.OAUTH(CLIENT_ID);

let pkce;
let code;

app.get("/", (req, res) => {
  pkce = pkceChallenge(128);

  const urlToRedirect = oauth.urlAuthorize(pkce.code_challenge);
  console.log(pkce);
  return res.redirect(urlToRedirect);
});

app.get("/oauth", (req, res) => {
  code = req.query.code;
  return res.send(req.query.code);
});

app.get("/showme", (req, res) => {
  return res.send({ pkce, code });
});

app.get("/accessToken", (req, res) => {
  oauth
    .accessToken(code, pkce.code_challenge)
    .then((response) => {
      res.send(response);
    })
    .catch((err) => {
      res.send(err);
    });
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

**Comment by anark1stx** [comment]
Thank you for replying, I tried your example and it is indeed working, although I'm not sure what I am doing wrong, the only difference between your example and mine is that your app is running with express while mine is running with Nuxtjs, maybe client side requests aren't allowed? In that case the error message would be different... Thank you again, I will keep trying and update if I can make it work :)

**Comment by anark1stx** [comment]
I think I will just create a backend with your example and host it with Heroku, my app will just make requests to it when it needs something, I wanted to avoid that since I don't know if the free version of heroku will allow many requests, and that's why I wanted to use this library from the client side.

**Comment by Chris-Kode** [comment]
This library is made to works in backend, because the MAL API official says that the use of this API in a web application need to be in a backend, and not in the front.

**Comment by anark1stx** [comment]
Oh you are right, I didn't saw that, I thought the API worked from the client as well like firebase, google or facebook, my bad then.
